spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
rag:
  app:
    vectorStorePath: /tmp/vectorstore.json
    documentsToLoad:
      - classpath:/top-100-imdb-movies.csv